apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travel-service.name" . }}
  labels:
    {{- include "travel-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "travel-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "travel-service.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "{{ .Values.port }}"
    spec:
      containers:
        - name: {{ include "travel-service.name" . }}
          image: {{ include "travel-service.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          env:
            {{- if eq .Values.datastore.type "postgres" }}
            - name: DB_HOST
              value: {{ .Values.datastore.dbHost | quote }}
            - name: DB_NAME
              value: {{ .Values.datastore.dbName | quote }}
            {{- end }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
